// <auto-generated />
using System;
using Labb2_Api_Angular.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2_Api_Angular.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221013153238_getid")]
    partial class getid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2_Api_Angular.Models.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("c98c58f5-4744-4049-8629-079a9935f6c1"),
                            DepartmentName = "Teknik"
                        },
                        new
                        {
                            DepartmentId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            DepartmentName = "Human resources"
                        },
                        new
                        {
                            DepartmentId = new Guid("2d4f9bbc-358b-49da-8bc4-43923e9147d6"),
                            DepartmentName = "SystemUtveckling"
                        });
                });

            modelBuilder.Entity("Labb2_Api_Angular.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("4d4b72c7-2b8c-405c-baad-b1c26cd946d7"),
                            Adress = "Långatan",
                            DepartmentId = new Guid("c98c58f5-4744-4049-8629-079a9935f6c1"),
                            Email = "Häftigmail.com",
                            FirstName = "Mattias",
                            Gender = "Male",
                            LastName = "Jonsson",
                            PhoneNumber = "0705454560",
                            Salary = 11500m
                        },
                        new
                        {
                            EmployeeId = new Guid("1f9e4b0c-05bc-45b9-b36e-c1daeb9034a9"),
                            Adress = "Halland",
                            DepartmentId = new Guid("c98c58f5-4744-4049-8629-079a9935f6c1"),
                            Email = "hotmail.com",
                            FirstName = "Daniel",
                            Gender = "Male",
                            LastName = "osrkarsson",
                            PhoneNumber = "5458522",
                            Salary = 13500m
                        },
                        new
                        {
                            EmployeeId = new Guid("b2fef0c9-5736-40d6-a718-41d30f9406ca"),
                            Adress = "Göteborg",
                            DepartmentId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Email = "gmail.com",
                            FirstName = "Edwin",
                            Gender = "Male",
                            LastName = "Nocco",
                            PhoneNumber = "05485036",
                            Salary = 35400m
                        },
                        new
                        {
                            EmployeeId = new Guid("42531374-5ebd-4e0f-9a8c-6f779224c592"),
                            Adress = "Umeå",
                            DepartmentId = new Guid("2d4f9bbc-358b-49da-8bc4-43923e9147d6"),
                            Email = "atelje.com",
                            FirstName = "Anna",
                            Gender = "Female",
                            LastName = "Myberg",
                            PhoneNumber = "04578521",
                            Salary = 36500m
                        });
                });

            modelBuilder.Entity("Labb2_Api_Angular.Models.Employee", b =>
                {
                    b.HasOne("Labb2_Api_Angular.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });
#pragma warning restore 612, 618
        }
    }
}
